Pandas Data Frame Basics:
- import pands library
- defined data frame 
- assigned path to data of the files

In [1]:
import pandas as pd
path_to_data = ('C:/Users/info/Dropbox/Python set/data files test/Radar.csv')

-Read Data frame
-head (specified columns in df, ie., view 5 columns)

In [9]:
df = pd.read_csv('C:/Users/info/Dropbox/Python set/data files test/Radar.csv')
df.head(5)

,Unnamed: 0,Name,Stocks,NSE: Stock Name,Unnamed: 4,Unnamed: 5,Unnamed: 6,Chartink,Unnamed: 8,Unnamed: 9,...,ITB /ONP(Retest)/ OTB(Flag),Wave 3/5,Relative Strenghth,Shallow/ Deep PullBack %,Major Resistance Zone X time Retested,Structure / Bounce back / Dynamic EMA support,Resting period after BO,50 EMA >/<,Comments,x
0,04/06/2025 15:30:03,0.0,AARTIDRUGS,NSE:AARTIDRUGS,AARTIDRUGS,chartink.com/stocks/AARTIDRUGS.html,chartink.com/stocks/AARTIDRUGS,AARTIDRUGS,www.screener.in/company/AARTIDRUGS/consolidated/,www.screener.in/company/AARTIDRUGS,...,NaN,-,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
1,NaN,0.0,METROBRAND,NSE:METROBRAND,METROBRAND,chartink.com/stocks/METROBRAND.html,chartink.com/stocks/METROBRAND,METROBRAND,www.screener.in/company/METROBRAND/consolidated/,www.screener.in/company/METROBRAND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
2,NaN,0.0,RAINBOW,NSE:RAINBOW,RAINBOW,chartink.com/stocks/RAINBOW.html,chartink.com/stocks/RAINBOW,RAINBOW,www.screener.in/company/RAINBOW/consolidated/,www.screener.in/company/RAINBOW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
3,NaN,0.0,LTFOODS,NSE:LTFOODS,LTFOODS,chartink.com/stocks/LTFOODS.html,chartink.com/stocks/LTFOODS,LTFOODS,www.screener.in/company/LTFOODS/consolidated/,www.screener.in/company/LTFOODS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
4,NaN,0.0,PRAJIND,NSE:PRAJIND,PRAJIND,chartink.com/stocks/PRAJIND.html,chartink.com/stocks/PRAJIND,PRAJIND,www.screener.in/company/PRAJIND/consolidated/,www.screener.in/company/PRAJIND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN

- tails: last 5 columns
- sample: random subset of data view
- columns: details
- row: details
- information: size, type of data, memory size
- describe: descriptive statistics data (mean ,max, min, ,std, 100%)
- shape: details of columns and rows

In [10]:
df.tail()

,Unnamed: 0,Name,Stocks,NSE: Stock Name,Unnamed: 4,Unnamed: 5,Unnamed: 6,Chartink,Unnamed: 8,Unnamed: 9,...,ITB /ONP(Retest)/ OTB(Flag),Wave 3/5,Relative Strenghth,Shallow/ Deep PullBack %,Major Resistance Zone X time Retested,Structure / Bounce back / Dynamic EMA support,Resting period after BO,50 EMA >/<,Comments,x
1378,NaN,NaN,NaN,Bhagyanagar Ind:,NaN,NaN,NaN,BHAGYANGR,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
1379,NaN,NaN,NaN,Patel Engineerin:,NaN,NaN,NaN,PATELENG,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
1380,NaN,NaN,NaN,Suven Pharma:,NaN,NaN,NaN,SUVENPHAR,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
1381,NaN,NaN,NaN,Kalyan Jewellers:,NaN,NaN,NaN,KALYANKJ,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
1382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SARDAEN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN

In [11]:
df.sample(5)

,Unnamed: 0,Name,Stocks,NSE: Stock Name,Unnamed: 4,Unnamed: 5,Unnamed: 6,Chartink,Unnamed: 8,Unnamed: 9,...,ITB /ONP(Retest)/ OTB(Flag),Wave 3/5,Relative Strenghth,Shallow/ Deep PullBack %,Major Resistance Zone X time Retested,Structure / Bounce back / Dynamic EMA support,Resting period after BO,50 EMA >/<,Comments,x
716,NaN,0.0,IDBI,NSE:IDBI,IDBI,chartink.com/stocks/IDBI.html,chartink.com/stocks/IDBI,IDBI,www.screener.in/company/IDBI/consolidated/,www.screener.in/company/IDBI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
273,NaN,0.0,PERSISTENT,NSE:PERSISTENT,PERSISTENT,chartink.com/stocks/PERSISTENT.html,chartink.com/stocks/PERSISTENT,PERSISTENT,www.screener.in/company/PERSISTENT/consolidated/,www.screener.in/company/PERSISTENT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
260,NaN,0.0,LT,NSE:LT,LT,chartink.com/stocks/LT.html,chartink.com/stocks/LT,LT,www.screener.in/company/LT/consolidated/,www.screener.in/company/LT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
378,NaN,0.0,NAVNETEDUL,NSE:NAVNETEDUL,NAVNETEDUL,chartink.com/stocks/NAVNETEDUL.html,chartink.com/stocks/NAVNETEDUL,NAVNETEDUL,www.screener.in/company/NAVNETEDUL/consolidated/,www.screener.in/company/NAVNETEDUL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN
461,NaN,0.0,STAR,NSE:STAR,STAR,chartink.com/stocks/STAR.html,chartink.com/stocks/STAR,STAR,www.screener.in/company/STAR/consolidated/,www.screener.in/company/STAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High,NaN,NaN

In [12]:
df.columns

Index(['Unnamed: 0', 'Name', 'Stocks', 'NSE: Stock Name', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Chartink', 'Unnamed: 8', 'Unnamed: 9',
       'Screener.in', 'LTP', 'High', '50 EMA', 'Alert Level', 'Study Done',
       'Volume Pop Out / Dried *', 'PBO(52WH) / ATH /MTY/ IPO',
       '>10 W EMA / > 30 W EMA', '>10 D / 21 D EMA',
       'Stage -2/Young/ % move upside', 'Base Count', 'WIB/3WCT',
       'Shake out done', 'Linear Up Move', 'Orderly Consolidate',
       'Tight Range %', 'Tight Volume % 50D SMA',
       'ITB /ONP(Retest)/ OTB(Flag)', 'Wave 3/5', 'Relative Strenghth',
       'Shallow/ Deep PullBack %', 'Major Resistance Zone X time Retested',
       'Structure / Bounce back / Dynamic EMA support',
       'Resting period after BO', '50 EMA >/<', 'Comments', 'x'],
      dtype='object')

In [13]:
df.info

<bound method DataFrame.info of                Unnamed: 0  Name      Stocks     NSE: Stock Name  Unnamed: 4  \
0     04/06/2025 15:30:03   0.0  AARTIDRUGS      NSE:AARTIDRUGS  AARTIDRUGS
1                     NaN   0.0  METROBRAND      NSE:METROBRAND  METROBRAND
2                     NaN   0.0     RAINBOW         NSE:RAINBOW     RAINBOW
3                     NaN   0.0     LTFOODS         NSE:LTFOODS     LTFOODS
4                     NaN   0.0     PRAJIND         NSE:PRAJIND     PRAJIND
...                   ...   ...         ...                 ...         ...
1378                  NaN   NaN         NaN   Bhagyanagar Ind:          NaN
1379                  NaN   NaN         NaN  Patel Engineerin:          NaN
1380                  NaN   NaN         NaN      Suven Pharma:          NaN
1381                  NaN   NaN         NaN   Kalyan Jewellers:         NaN
1382                  NaN   NaN         NaN                 NaN         NaN

                               Unnamed: 5                      Unnamed: 6  \
0     chartink.com/stocks/AARTIDRUGS.html  chartink.com/stocks/AARTIDRUGS
1     chartink.com/stocks/METROBRAND.html  chartink.com/stocks/METROBRAND
2        chartink.com/stocks/RAINBOW.html     chartink.com/stocks/RAINBOW
3        chartink.com/stocks/LTFOODS.html     chartink.com/stocks/LTFOODS
4        chartink.com/stocks/PRAJIND.html     chartink.com/stocks/PRAJIND
...                                   ...                             ...
1378                                  NaN                             NaN
1379                                  NaN                             NaN
1380                                  NaN                             NaN
1381                                  NaN                             NaN
1382                                  NaN                             NaN

         Chartink                                        Unnamed: 8  \
0      AARTIDRUGS  www.screener.in/company/AARTIDRUGS/consolidated/
1      METROBRAND  www.screener.in/company/METROBRAND/consolidated/
2         RAINBOW     www.screener.in/company/RAINBOW/consolidated/
3         LTFOODS     www.screener.in/company/LTFOODS/consolidated/
4         PRAJIND     www.screener.in/company/PRAJIND/consolidated/
...           ...                                               ...
1378    BHAGYANGR                                               NaN
1379     PATELENG                                               NaN
1380    SUVENPHAR                                               NaN
1381     KALYANKJ                                               NaN
1382      SARDAEN                                               NaN

                              Unnamed: 9  ... ITB /ONP(Retest)/ OTB(Flag)  \
0     www.screener.in/company/AARTIDRUGS  ...                         NaN
1     www.screener.in/company/METROBRAND  ...                         NaN
2        www.screener.in/company/RAINBOW  ...                         NaN
3        www.screener.in/company/LTFOODS  ...                         NaN
4        www.screener.in/company/PRAJIND  ...                         NaN
...                                  ...  ...                         ...
1378                                 NaN  ...                         NaN
1379                                 NaN  ...                         NaN
1380                                 NaN  ...                         NaN
1381                                 NaN  ...                         NaN
1382                                 NaN  ...                         NaN

      Wave 3/5  Relative Strenghth  Shallow/ Deep PullBack %  \
0            -                 NaN                       NaN
1          NaN                 NaN                       NaN
2          NaN                 NaN                       NaN
3          NaN                 NaN                       NaN
4          NaN                 NaN                       NaN
...        ...                 ...                       ...
1378       NaN                 NaN                       NaN
1379       NaN                 NaN                       NaN
1380       NaN                 NaN                       NaN
1381       NaN                 NaN                       NaN
1382       NaN                 NaN                       NaN

      Major Resistance Zone X time Retested  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
1378                                    NaN
1379                                    NaN
1380                                    NaN
1381                                    NaN
1382                                    NaN

     Structure / Bounce back / Dynamic EMA support Resting period after BO  \
0                                              NaN                     NaN
1                                              NaN                     NaN
2                                              NaN                     NaN
3                                              NaN                     NaN
4                                              NaN                     NaN
...                                            ...                     ...
1378                                           NaN                     NaN
1379                                           NaN                     NaN
1380                                           NaN                     NaN
1381                                           NaN                     NaN
1382                                           NaN                     NaN

      50 EMA >/< Comments   x
0           High      NaN NaN
1           High      NaN NaN
2           High      NaN NaN
3           High      NaN NaN
4           High      NaN NaN
...          ...      ...  ..
1378         Low      NaN NaN
1379         Low      NaN NaN
1380         Low      NaN NaN
1381         Low      NaN NaN
1382         Low      NaN NaN

[1383 rows x 38 columns]>

In [16]:
df.index

RangeIndex(start=0, stop=1383, step=1)

In [18]:
df.shape

(1383, 38)